version: '3.3'
services:
  velociraptor:
    container_name: velociraptor
    image: velociraptor:latest
    volumes:
      - ./velociraptor:/velociraptor/:rw
    environment:
      - VELOX_USER=${VELOX_USER}
      - VELOX_PASSWORD=${VELOX_PASSWORD}
      - VELOX_ROLE=${VELOX_ROLE}
      - VELOX_SERVER_URL=${VELOX_SERVER_URL}
      - VELOX_FRONTEND_HOSTNAME=${VELOX_FRONTEND_HOSTNAME}
      - VELOX_API_HOSTNAME=velociraptor
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
    networks:
      - velo

  velociraptor_minion:
    container_name: velociraptor_minion
    image: velociraptor:latest
    profiles:
      - minion
    volumes:
      - ./velociraptor:/velociraptor/:rw
    environment:
      - VELOX_MODE=minion
      - VELOX_SERVER_PORT=8002
    ports:
      - "8002:8002"
    networks:
      - velo

networks:
  velo: